import type { Metadata, Viewport } from "next";
import { readFileSync } from "fs";
import { join } from "path";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import "./globals.css";
import { SITE_NAME, SITE_URL } from "@/lib/site";
import { ReceiptsProvider } from "@/components/receipts-toggle";
import { CommandPalette } from "@/components/search/command-palette";
import { SiteHeader } from "@/components/site-header";
import { FooterCorpus } from "@/components/footer-corpus";
import { websiteJsonLd, safeJsonLd } from "@/lib/jsonld";
import { siteFeedLinks } from "@/lib/feeds";
import { Analytics } from "@vercel/analytics/next";

// Read built_at + corpus counts from site_meta.json at build time
function getSiteMetaPartial(): { builtAt: string; counts: { programs: number; citations: number; companies: number; agencies: number } | null } {
  try {
    const metaPath = join(process.cwd(), "..", "data", "site", "json", "site_meta.json");
    const meta = JSON.parse(readFileSync(metaPath, "utf8"));
    return { builtAt: meta.built_at ?? "", counts: meta.counts ?? null };
  } catch {
    return { builtAt: "", counts: null };
  }
}

const { builtAt, counts } = getSiteMetaPartial();

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: SITE_NAME,
    template: `%s | ${SITE_NAME}`,
  },
  description:
    "Federal defense budget data — every number citation-backed with PDF page-level provenance.",
  // Real favicon.ico in public/ (backlog #21 — browsers request it by
  // convention; it 404'd through 5H live verification). Generated by
  // scripts/generate-favicon.mjs from the OG-card brand mark.
  icons: { icon: "/favicon.ico", shortcut: "/favicon.ico" },
};

// Sprint C Task C7 (ROADMAP #66) — `color-scheme: light dark` tells the UA
// both schemes are supported, so form controls, scrollbars, and the
// browser's own chrome (not reachable by globals.css's custom properties)
// follow prefers-color-scheme the same way the page body now does. Next's
// Viewport API (separate from Metadata since 14) is the supported way to
// emit <meta name="color-scheme">; it renders identically under `output:
// export` since it's resolved at build time, not per-request.
export const viewport: Viewport = {
  colorScheme: "light dark",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* §P1-8 feed autodiscovery, site-wide. Rendered as elements (React
            hoists them into <head>) rather than through metadata.alternates:
            Next merges metadata field-by-field, so every page that declares
            its own canonical would REPLACE the layout's alternates and
            silently drop the subscription link. */}
        {siteFeedLinks().map((l) => (
          <link key={l.href} rel={l.rel} type={l.type} href={l.href} title={l.title} />
        ))}
        {/* The type system's two critical-path faces (the LCP heading is the
            serif; the html default is the sans), preloaded so the swap lands
            before first paint. The mono (identifiers) and the italic are
            CSS-discovered: a page where no identifier paints does not pay
            for the face (gate 26 leg (0) asks the browser to load each face
            from the origin rather than requiring it on the critical path).
            Paths carry a version directory and ship with an immutable cache
            header (public/vercel.json); a re-vendor changes the directory,
            never the bytes at a path. */}
        <link rel="preload" href="/fonts/source-serif-4/v14/SourceSerif4Variable-Roman.woff2" as="font" type="font/woff2" crossOrigin="anonymous" />
        <link rel="preload" href="/fonts/source-sans-3/v19/SourceSans3Variable-Roman.woff2" as="font" type="font/woff2" crossOrigin="anonymous" />
        {/* Site-wide WebSite + SearchAction JSON-LD */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: safeJsonLd(websiteJsonLd()) }}
        />
        <ReceiptsProvider>
          {/* Global two-tier search dialog */}
          <CommandPalette />
          {/* Skip link for keyboard / screen reader users */}
          <a href="#main-content" className="skip-to-content">
            Skip to content
          </a>

          <SiteHeader />
          <main id="main-content" tabIndex={-1}>
            {children}
          </main>

          {/* ── Site Footer ── */}
          <footer className="site-footer">
            <div className="spine">
              <div className="site-footer-top">
                <div>
                  <Link href="/" className="site-footer-brand">{SITE_NAME}</Link>
                  {/* The corpus statement, ONE sentence with the four linked
                      figures (round-5: the homepage stats strip is dead; the
                      data-stat contract — linkgraph gate: every [data-stat]
                      is or contains an <a> — lives here). No brand blurb.
                      HOMEPAGE ONLY (FooterCorpus pathname-checks): on every
                      other route the sentence is dead weight against gate
                      1's ceilings — it put /companies/ 65 bytes and
                      /coverage/ 90 bytes over theirs. */}
                  <FooterCorpus counts={counts} />
                </div>
                <nav aria-label="Footer" className="site-footer-links">
                  <div><strong className="t-label">Explore</strong><Link href="/explore/">Visual field guide</Link><Link href="/programs/">Programs</Link><Link href="/agency/">Agencies</Link><Link href="/district/">Districts</Link></div>
                  <div><strong className="t-label">Investigate</strong><Link href="/feed/">Changes &amp; signals</Link><Link href="/companies/">Companies</Link><Link href="/filings/">Lobbying filings</Link><Link href="/years/">Compare years</Link></div>
                  <div><strong className="t-label">Verify &amp; reuse</strong><Link href="/methodology/">Methodology</Link><Link href="/coverage/">Coverage</Link><Link href="/glossary/">Glossary</Link><Link href="/downloads/">Downloads</Link></div>
                </nav>
              </div>
              <div className="site-footer-bottom">
                <span>{builtAt && <>Site export <time dateTime={builtAt}>{new Date(builtAt).toLocaleDateString("en-US", {year:"numeric",month:"long",day:"numeric"})}</time>. </>}Source dates vary by dataset.</span>
                <div><Link href="/about/">About</Link><a href="mailto:andes.han.lee@gmail.com">Contact</a><a href="https://creativecommons.org/publicdomain/zero/1.0/" rel="license noopener noreferrer" target="_blank">Data: CC0 1.0 <ArrowUpRight size="1em" aria-hidden /></a></div>
              </div>
            </div>
          </footer>
        </ReceiptsProvider>
        {/* Vercel Web Analytics. Renders NOTHING — the component returns
            null and appends <script defer src="/_vercel/insights/script.js">
            from an effect — so it adds no markup to any page; its whole
            page-weight cost is the client-reference the root layout now
            carries in the RSC flight payload, weighed against gate 1's
            budget in the same change that added it (see the note on
            scripts/gates/build.mjs's PAGE_WEIGHT_BUDGET).

            SAME-ORIGIN, AND COOKIELESS. In a production build the script
            src is the relative /_vercel/insights/script.js and the beacon
            posts to /_vercel/insights/* — no third-party host is contacted
            from a reader's browser, so nothing here needs a CSP exception.
            Vercel Web Analytics sets no cookies: a visitor is identified by
            a hash derived from the incoming request, discarded after 24
            hours (vercel.com/docs/analytics/privacy-policy). That is the
            only reason it is acceptable on a public-interest transparency
            site, and it is why this is Analytics alone — anything that sets
            a cookie or collects PII does not go in this layout without
            being argued for first.

            The /next entry (not /react) is deliberate: it reads the
            PARAMETERISED route from next/navigation, so 1,993 program pages
            report as /program/[peBli] instead of 1,993 separate paths. */}
        <Analytics />
      </body>
    </html>
  );
}
