"""Metric-matched fallback faces for the site type system.

Emits the @font-face `local()` block for globals.css: one fallback family per
vendored face, with size-adjust / ascent-override / descent-override computed
from the fonts' own tables so a fallback paints the same line box as the
webfont and the swap does not shift layout (gate 7 holds CLS <= 0.1).

Method (per fallback): size-adjust = advance(webfont, SAMPLE) / advance(fallback, SAMPLE);
ascent-override = (webfont hhea.ascent / UPM) / size-adjust; descent-override likewise; line-gap 0.
Run: uvx --with brotli --from fonttools python scripts/fonts/fallback-metrics.py
Only faces actually installed on this machine are measured; others are omitted.
"""
from fontTools.ttLib import TTFont, TTCollection
import glob, os, sys

SAMPLE = "The FY2026 request for 0606301D8Z is $10.7B, up 17.8% from FY2025 — see Exhibit R-2, page 14."
WEB = {
    "SS4": "public/fonts/source-serif-4/v14/SourceSerif4Variable-Roman.woff2",
    "SS3": "public/fonts/source-sans-3/v19/SourceSans3Variable-Roman.woff2",
    "SCP": "public/fonts/source-code-pro/v31/SourceCodePro-Variable-Roman.woff2",
}
# (family-name suffix, local() name, candidate files, subfamily to pick from a .ttc)
FALLBACKS = {
    "SS4": [("Iowan", "Iowan Old Style", ["/System/Library/Fonts/Supplemental/Iowan Old Style.ttc"], "Roman"),
            ("Georgia", "Georgia", ["/System/Library/Fonts/Supplemental/Georgia.ttf"], None),
            ("Palatino", "Palatino", ["/System/Library/Fonts/Palatino.ttc"], "Regular")],
    "SS3": [("Avenir", "Avenir Next", ["/System/Library/Fonts/Avenir Next.ttc"], "Regular"),
            ("Arial", "Arial", ["/System/Library/Fonts/Supplemental/Arial.ttf"], None)],
    "SCP": [("SFMono", "SF Mono", ["/System/Library/Fonts/SFNSMono.ttf", "/System/Library/Fonts/SFMono-Regular.otf"], None),
            ("Menlo", "Menlo", ["/System/Library/Fonts/Menlo.ttc"], "Regular"),
            ("Courier", "Courier New", ["/System/Library/Fonts/Supplemental/Courier New.ttf"], None)],
}

def load(path, sub):
    if path.endswith(".ttc"):
        for f in TTCollection(path).fonts:
            if sub is None or f["name"].getDebugName(2) == sub:
                return f
        return None
    return TTFont(path)

def advance(f, text):
    cmap = f.getBestCmap(); hm = f["hmtx"]; upm = f["head"].unitsPerEm
    return sum(hm[cmap[ord(c)]][0] for c in text if ord(c) in cmap) / upm, sum(1 for c in text if ord(c) in cmap)

out = ["/* @fallback-metrics:start — generated by scripts/fonts/fallback-metrics.py; do not edit by hand */"]
for key, webpath in WEB.items():
    w = TTFont(webpath); wa, wn = advance(w, SAMPLE)
    for suffix, local, files, sub in FALLBACKS[key]:
        path = next((p for p in files if os.path.exists(p)), None)
        if not path: continue
        f = load(path, sub)
        if f is None: continue
        fa, fn = advance(f, SAMPLE)
        if fn != wn:  # compare on the glyphs both fonts have
            common = "".join(c for c in SAMPLE if ord(c) in w.getBestCmap() and ord(c) in f.getBestCmap())
            wa, _ = advance(w, common); fa, _ = advance(f, common)
        sa = wa / fa
        # The overrides describe the WEBFONT's line box, scaled so the fallback
        # (drawn at size-adjust) paints the same ascent/descent the webfont will.
        upm = w["head"].unitsPerEm; hh = w["hhea"]
        asc = (hh.ascent / upm) / sa; desc = (abs(hh.descent) / upm) / sa
        out.append(f'@font-face {{ font-family: "{key} Fallback {suffix}"; src: local("{local}"); size-adjust: {sa*100:.2f}%; ascent-override: {asc*100:.2f}%; descent-override: {desc*100:.2f}%; line-gap-override: 0%; }}')
out.append("/* @fallback-metrics:end */")
print("\n".join(out))
