import type { KnowledgeSource, VariantContext } from "./f15-knowledge-types";

/**
 * Aircraft context is independent of a budget-to-configuration crosswalk.
 * Historical examples stay dated; a research aircraft or an upgrade milestone
 * does not establish the equipment fitted to every airframe of that variant.
 */
export const VARIANT_CONTEXT_SOURCES: KnowledgeSource[] = [
  {
    id: "variant-usaf-eagle-facts",
    title: "F-15 Eagle fact sheet (current as of April 2019)",
    publisher: "U.S. Air Force",
    url: "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104501/f-15-eagle/",
    published: null,
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "variant-usaf-streak-eagle",
    title: "McDonnell Douglas F-15 Streak Eagle",
    publisher: "National Museum of the U.S. Air Force",
    url: "https://www.nationalmuseum.af.mil/Visit/Museum-Exhibits/Fact-Sheets/Display/Article/197972/mcdonnell-douglas-f-15-streak-eagle/",
    published: null,
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "variant-142fw-alpha-retirement",
    title: "Final F-15A model retired by the Air Force",
    publisher: "142nd Fighter Wing",
    url: "https://www.142wg.ang.af.mil/News/Article-Display/Article/438215/final-f-15a-model-retired-by-the-air-force/",
    published: "2011-04-05",
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "variant-nasa-b-testbed",
    title: "F-15B Aeronautics Research Test Bed",
    publisher: "NASA Armstrong Flight Research Center",
    url: "https://www.nasa.gov/aeronautics/f-15b-test-bed/",
    published: "2015-06-03",
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "variant-sheppard-maintenance-training",
    title: "Newer F-15s enhance maintenance training",
    publisher: "U.S. Air Force / 82nd Training Wing",
    url: "https://www.af.mil/News/Article-Display/Article/116056/newer-f-15s-enhance-maintenance-training/",
    published: "2010-07-26",
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "variant-ang-aesa-rollout",
    title: "New F-15 radar debuts at Florida's 125th Fighter Wing",
    publisher: "National Guard Bureau",
    url: "https://www.125fw.ang.af.mil/News/Article-Display/Article/449716/new-f-15-radar-debuts-at-floridas-125th-fighter-wing/",
    published: "2010-05-06",
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "variant-boeing-cd-aesa-contract",
    title: "Boeing, Air Force, Air National Guard roll out first operational F-15C with enhanced radar",
    publisher: "Boeing",
    url: "https://boeing.mediaroom.com/2010-04-12-Boeing-Air-Force-Air-National-Guard-Roll-Out-1st-Operational-F-15C-with-Enhanced-Radar",
    published: "2010-04-12",
    accessed: "2026-09-09",
    evidence: "manufacturer",
  },
  {
    id: "variant-robins-structural-teardown",
    title: "Disassembly project to provide data to F-15 maintainers",
    publisher: "Air Force Materiel Command / 78th Air Base Wing",
    url: "https://www.afmc.af.mil/News/Article-Display/Article/154449/disassembly-project-to-provide-data-to-f-15-maintainers/",
    published: "2009-07-10",
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "variant-nasa-d-characteristics",
    title: "Support Aircraft and Maintenance Operations Characteristics",
    publisher: "NASA",
    url: "https://www.nasa.gov/directorates/armd/iasp/fdc/support-aircraft-and-maintenance-operations-characteristics/",
    published: "2016-05-11",
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "variant-acc-pilot-currency",
    title: "F-15 pilots begin return to currency",
    publisher: "Air Combat Command",
    url: "https://www.acc.af.mil/News/Article-Display/Article/202253/f-15-pilots-begin-return-to-currency/",
    published: "2008-01-09",
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "variant-usaf-strike-eagle-facts",
    title: "F-15E Strike Eagle fact sheet (current as of April 2019)",
    publisher: "U.S. Air Force",
    url: "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104499/f-15e-strike-eagle/",
    published: null,
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "variant-eglin-apg82-flight",
    title: "F-15E flies with new radar system",
    publisher: "U.S. Air Force / Eglin Air Force Base",
    url: "https://www.af.mil/News/Article-Display/Article/114356/f-15e-flies-with-new-radar-system/",
    published: "2011-01-24",
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "variant-aflcmc-epawss-delivery",
    title: "USAF delivers first EPAWSS-modified F-15E to RAF Lakenheath",
    publisher: "Air Force Life Cycle Management Center",
    url: "https://www.aflcmc.af.mil/NEWS/Article-Display/Article/4032783/usaf-delivers-first-epawss-modified-f-15e-strike-eagle-to-raf-lakenheath-ab-uk/",
    published: "2025-01-17",
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "variant-seymour-fuel-maintenance",
    title: "4th CMS fuels Airmen maintain F-15E external and conformal fuel tanks",
    publisher: "Seymour Johnson Air Force Base",
    url: "https://www.seymourjohnson.af.mil/News/Article-Display/Article/2577712/4th-cms-fuels-airmen-maintain-f-15e-external-and-conformal-fuel-tanks/",
    published: "2021-04-19",
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "variant-aflcmc-first-ex",
    title: "Air Force receives first F-15EX",
    publisher: "Air Force Life Cycle Management Center",
    url: "https://www.af.mil/News/Features/Article/2534008/air-force-receives-first-f-15ex/",
    published: "2021-03-11",
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "variant-eglin-ex-preparation",
    title: "Team Eglin prepared, ready for F-15EX",
    publisher: "Air Force Life Cycle Management Center / Eglin Air Force Base",
    url: "https://www.aflcmc.af.mil/News/Article-Display/Article/2292415/team-eglin-prepared-ready-for-f-15ex/",
    published: "2020-07-28",
    accessed: "2026-09-09",
    evidence: "government",
  },
];

export const VARIANT_CONTEXTS: VariantContext[] = [
  {
    variant: "A",
    topic: "airframe",
    title: "The original air-superiority Eagle",
    text: "The F-15A established the Eagle's twin-engine air-superiority design. High thrust and a large wing relative to aircraft weight supported rapid climbs and tight turns. The specially lightened Streak Eagle, an early F-15A, demonstrated that design by setting eight time-to-climb records in 1975; it was a test aircraft, not a standard operational configuration.",
    sourceIds: ["variant-usaf-streak-eagle"],
  },
  {
    variant: "A",
    topic: "cockpit",
    title: "One pilot, integrated flight and weapons controls",
    text: "The A model seats one pilot. A head-up display brings flight and targeting information into the forward view; throttle and stick controls support weapon selection. This is the Eagle's single-pilot design approach. Individual displays and equipment changed with later aircraft and retrofits.",
    sourceIds: ["variant-usaf-eagle-facts"],
  },
  {
    variant: "A",
    topic: "sensors",
    title: "Seeing targets above and below the horizon",
    text: "The legacy Eagle used pulse-Doppler radar to track aircraft against sky and ground clutter. Radar, a central computer, and electronic threat warning supported air-to-air missions. These are documented family capabilities; they do not imply that an early A model carried later AESA or EPAWSS upgrades.",
    sourceIds: ["variant-usaf-eagle-facts"],
  },
  {
    variant: "A",
    topic: "support",
    title: "The crews behind a long service life",
    text: "A 142nd Fighter Wing retrospective describes A-model crew chiefs keeping aging aircraft ready for air-defense missions and deployments, then preparing them for retirement as C/D aircraft arrived. Its account follows inspections, maintenance labor, and transfers to storage or museums: useful evidence of the work around a fighter beyond buying the airframe.",
    sourceIds: ["variant-142fw-alpha-retirement"],
  },
  {
    variant: "B",
    topic: "airframe",
    title: "A two-seat Eagle with a second life in research",
    text: "The B model provides two seats in the Eagle airframe. NASA's modified F-15B shows how that platform could take on another job: carrying interchangeable flight-test fixtures beneath its fuselage. Those fixtures supported aerodynamic and propulsion experiments, including testing experimental engine technology in flight. NASA's additions belong to its research aircraft, not every F-15B.",
    sourceIds: ["variant-nasa-b-testbed"],
  },
  {
    variant: "B",
    topic: "cockpit",
    title: "A rear seat that can support the mission",
    text: "The two-seat layout also made the B model useful for research work. In NASA's modified testbed, the person in the rear cockpit monitored an onboard video system that sent flight imagery to researchers on the ground. That is a documented example of adapting the second station, rather than treating every two-seat Eagle as a Strike Eagle.",
    sourceIds: ["variant-nasa-b-testbed"],
  },
  {
    variant: "B",
    topic: "sensors",
    title: "Measuring the air, not just tracking aircraft",
    text: "NASA equipped its F-15B with a research air-data system, GPS, a probe on a nose boom, a digital recorder, and telemetry antennas. Together, those instruments let engineers measure flight conditions and return experiment data. This is a specific research configuration, a useful example of how sensor equipment changes with an aircraft's assignment.",
    sourceIds: ["variant-nasa-b-testbed"],
  },
  {
    variant: "B",
    topic: "support",
    title: "Retired aircraft became hands-on classrooms",
    text: "Sheppard Air Force Base used A/B Eagles to teach aircraft maintenance before replacing them with C/D ground trainers in 2010. Instructors explained that older cockpit controls and launchers no longer matched operational jets. The story shows why training aircraft, course materials, and technician proficiency must evolve alongside fleet equipment.",
    sourceIds: ["variant-sheppard-maintenance-training"],
  },
  {
    variant: "C",
    topic: "airframe",
    title: "More fuel within the air-superiority design",
    text: "The single-seat C entered Air Force service in 1979. Production improvements added internal fuel, provision for conformal fuel tanks, and a higher permitted takeoff weight. Its familiar outline hides changes in endurance and loading; provision for tanks does not establish that every aircraft carried them.",
    sourceIds: ["variant-usaf-eagle-facts"],
  },
  {
    variant: "C",
    topic: "cockpit",
    title: "Cockpit upgrades changed the training task",
    text: "In 2010, Air Force maintenance instructors singled out the C/D models' multipurpose color display and relocated controls as differences from the older B-model trainers. Updating the training fleet let students practice on the equipment they would maintain in service. The C-model cockpit evolved over time rather than remaining frozen at its original delivery standard.",
    sourceIds: ["variant-sheppard-maintenance-training"],
  },
  {
    variant: "C",
    topic: "sensors",
    title: "An electronic beam replaces a moving radar dish",
    text: "The Air National Guard unveiled an APG-63(V)3 AESA-equipped F-15C in Florida in April 2010, with Oregon and Louisiana next in its fielding plan. Electronic beam steering supported faster scanning and multiple-target tracking while removing mechanical steering. This was an upgrade program; equipment still depends on the particular aircraft and date.",
    sourceIds: ["variant-ang-aesa-rollout"],
  },
  {
    variant: "C",
    topic: "support",
    title: "Finding fatigue before it becomes a fleet problem",
    text: "In 2009, the Air Force described an F-15C full-scale fatigue test at Boeing alongside a planned C-model teardown. Simulated flight loads and detailed examinations of aging structures were intended to improve depot inspection schedules. This is the engineering work behind keeping an older fighter available, distinct from adding a new weapon or radar.",
    sourceIds: ["variant-robins-structural-teardown"],
  },
  {
    variant: "D",
    topic: "airframe",
    title: "The two-seat airframe also serves science",
    text: "NASA describes its F-15D as a two-seat aircraft powered by two Pratt & Whitney F100 engines. Three D models transferred from Tyndall in 2010 for flight research and mission support. Their speed and camera-carrying role illustrate another use of the same aircraft family beyond an operational fighter squadron.",
    sourceIds: ["variant-nasa-d-characteristics"],
  },
  {
    variant: "D",
    topic: "cockpit",
    title: "An instructor can fly in the back seat",
    text: "The D model's second seat supports pilot instruction and requalification. During the fleet's return to flying in 2008, Air Combat Command described instructors riding in an F-15D's rear seat to sign off less-experienced pilots. It is a concrete training use for the extra cockpit, with a different crew task from the F-15E's weapons-system officer.",
    sourceIds: ["variant-acc-pilot-currency", "variant-usaf-strike-eagle-facts"],
  },
  {
    variant: "D",
    topic: "sensors",
    title: "The D also appears in the radar-upgrade program",
    text: "Boeing's April 2010 announcement identifies F-15C/D aircraft in its APG-63(V)3 AESA upgrade contract. The radar combines electronically steered sensing with a built-in antenna test function intended to aid maintenance. The contract establishes a C/D modernization effort; it does not establish that every D model received the radar.",
    sourceIds: ["variant-boeing-cd-aesa-contract"],
  },
  {
    variant: "D",
    topic: "support",
    title: "One aircraft can teach a fleet how it ages",
    text: "A 2009 F-15D teardown near Robins examined internal areas beyond a normal depot visit. S&K Technologies removed parts for progressively deeper inspection; cracks or corrosion could trigger laboratory analysis. The results were intended to adjust maintenance requirements for the wider Eagle fleet, turning a retired airframe into evidence for future inspections.",
    sourceIds: ["variant-robins-structural-teardown"],
  },
  {
    variant: "E",
    topic: "airframe",
    title: "An Eagle adapted for the strike mission",
    text: "The two-seat Strike Eagle combines air-to-air and air-to-ground roles. Conformal fuel tanks follow the sides of the fuselage, carrying fuel and providing short weapon pylons. The Air Force identifies Pratt & Whitney F100-PW-220 or -229 engines for this variant. Those fuel tanks and mission equipment help explain its different profile.",
    sourceIds: ["variant-usaf-strike-eagle-facts"],
  },
  {
    variant: "E",
    topic: "cockpit",
    title: "A pilot and a weapons-system officer share the work",
    text: "The E's rear station is a mission workstation. The weapons-system officer can view radar, infrared, electronic-warfare, aircraft-status, and navigation information, then select targets and refine targeting data. The pilot has flight and tactical displays forward. This division of work is why the second cockpit matters to the strike mission.",
    sourceIds: ["variant-usaf-strike-eagle-facts"],
  },
  {
    variant: "E",
    topic: "sensors",
    title: "Radar modernization and electronic protection",
    text: "The Air Force flight-tested the APG-82(V)1 AESA radar on an F-15E in 2011 as a replacement for the mechanically scanned APG-70. Another upgrade, EPAWSS, reached its first operational F-15E delivery at RAF Lakenheath in January 2025. These are separate modernization milestones, not evidence that every E model received both systems at once.",
    sourceIds: ["variant-eglin-apg82-flight", "variant-aflcmc-epawss-delivery"],
  },
  {
    variant: "E",
    topic: "support",
    title: "Fuel tanks bring their own maintenance work",
    text: "Seymour Johnson's fuel-system technicians documented draining and testing F-15E conformal tanks, inspecting external tanks, and sealing an engine-to-airframe fuel manifold in April 2021. The aircraft's range depends on this less-visible work: handling equipment, test instruments, inspections, and people maintaining the fuel system around the flight schedule.",
    sourceIds: ["variant-seymour-fuel-maintenance"],
  },
  {
    variant: "EX",
    topic: "airframe",
    title: "A new-build Eagle with a digital foundation",
    text: "The Air Force accepted its first F-15EX in March 2021 to begin replacing aging C/D aircraft. It retains the Eagle family form but combines a two-seat airframe with digital flight controls and updated mission systems. Eglin's preparation report traces the design to F-15 versions previously built for foreign military customers.",
    sourceIds: ["variant-aflcmc-first-ex", "variant-eglin-ex-preparation"],
  },
  {
    variant: "EX",
    topic: "cockpit",
    title: "Two seats, digital displays, and fly-by-wire controls",
    text: "The EX has two seats but can be operated by one pilot, according to the Air Force's first-delivery announcement. Digital cockpit displays and fly-by-wire controls distinguish it from the older C/D fleet. Eglin described touch displays and simulator familiarization as part of preparing aircrew for the new interface.",
    sourceIds: ["variant-aflcmc-first-ex", "variant-eglin-ex-preparation"],
  },
  {
    variant: "EX",
    topic: "sensors",
    title: "Electronic protection is built into the EX",
    text: "EPAWSS is included in new F-15EX production. The Air Force describes it as detecting, identifying, and locating threats, then disrupting their operation. BAE Systems manufactures the system and Boeing integrates it; software updates can extend its capability. This links the aircraft's survivability equipment to both a supplier and an ongoing modernization program.",
    sourceIds: ["variant-aflcmc-epawss-delivery"],
  },
  {
    variant: "EX",
    topic: "support",
    title: "Fielding a jet includes training and ground equipment",
    text: "Eglin's EX preparations included classroom instruction, hands-on maintainer training, aircrew training, and a simulator. The first-lot contract also covered spares, support equipment, technical data, and technical support. Those activities explain why an aircraft procurement package buys more than metal: a squadron needs the means to operate and maintain its new jets.",
    sourceIds: ["variant-eglin-ex-preparation"],
  },
];
