import type { KnowledgeSource, SystemContext } from "./f15-knowledge-types";

/**
 * Dated public descriptions of suppliers, systems and related work.
 * These relationships do not allocate a budget line to a supplier or component.
 * An announcement is evidence that something was announced, not that it was fielded.
 */
export const SYSTEM_CONTEXT_SOURCES: KnowledgeSource[] = [
  {
    id: "sys-usaf-eagle-facts",
    title: "F-15 Eagle fact sheet · historical configuration",
    publisher: "U.S. Air Force",
    url: "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104501/f-15-eagle/",
    published: null,
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "sys-usaf-strike-facts",
    title: "F-15E Strike Eagle fact sheet · engines and mission systems",
    publisher: "U.S. Air Force",
    url: "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104499/f-15e-strike-eagle/",
    published: null,
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "sys-usaf-f110-contract",
    title: "US Air Force awards F-15EX engine contract",
    publisher: "Secretary of the Air Force Public Affairs",
    url: "https://www.af.mil/News/Features/Article/2827633/us-air-force-awards-f-15ex-engine-contract/",
    published: "2021-10-29",
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "sys-ge-f110",
    title: "F110 engine · F-15EX propulsion",
    publisher: "GE Aerospace",
    url: "https://www.geaerospace.com/military-defense/engines/f110",
    published: null,
    accessed: "2026-09-09",
    evidence: "manufacturer",
  },
  {
    id: "sys-usaf-f100",
    title: "Pratt & Whitney F100-PW-220",
    publisher: "National Museum of the U.S. Air Force",
    url: "https://www.nationalmuseum.af.mil/Visit/Museum-Exhibits/Fact-Sheets/Display/Article/196437/pratt-whitney-f100-pw-220/",
    published: null,
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "sys-raytheon-apg82",
    title: "AN/APG-82(V)1 AESA radar",
    publisher: "Raytheon · RTX",
    url: "https://www.rtx.com/raytheon/what-we-do/air/apg82v1",
    published: null,
    accessed: "2026-09-09",
    evidence: "manufacturer",
  },
  {
    id: "sys-usaf-radar-first-flight",
    title: "F-15E flies with new radar system",
    publisher: "U.S. Air Force · Eglin AFB Public Affairs",
    url: "https://www.af.mil/News/Article-Display/Article/114356/f-15e-flies-with-new-radar-system/",
    published: "2011-01-24",
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "sys-ex-sar2022",
    title: "F-15EX Selected Acquisition Report · December 2022, pp. 14–16",
    publisher: "U.S. Department of Defense",
    url: "https://www.esd.whs.mil/Portals/54/Documents/FOID/Reading%20Room/Selected_Acquisition_Reports/FY_2022_SARS/F-15%20EX%20%28Initial%29_SAR_DEC_2022.pdf#page=14",
    published: null,
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "sys-ex-msar2023",
    title: "F-15EX Modernized Selected Acquisition Report · effective December 31, 2023, pp. 7–8",
    publisher: "U.S. Department of Defense",
    url: "https://www.esd.whs.mil/Portals/54/Documents/FOID/Reading%20Room/Selected_Acquisition_Reports/FY_2023_SARS/F-15_EX_MDAP_MSAR_Dec_2023.pdf#page=7",
    published: null,
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "sys-bae-flight-controls",
    title: "BAE Systems to upgrade flight control computers for F-15EX and F/A-18E/F fighters",
    publisher: "BAE Systems",
    url: "https://www.baesystems.com/en-us/article/bae-systems-to-upgrade-flight-control-computers-for-f-15ex-and-f-a-18e-f-fighters",
    published: "2024-08-20",
    accessed: "2026-09-09",
    evidence: "manufacturer",
  },
  {
    id: "sys-usaf-epawss-industry",
    title: "USAF delivers first EPAWSS-modified F-15E Strike Eagle",
    publisher: "U.S. Air Force · Fighters and Advanced Aircraft Directorate",
    url: "https://www.wpafb.af.mil/News/Article-Display/Article/4033163/usaf-delivers-first-epawss-modified-f-15e-strike-eagle/",
    published: "2025-01-17",
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "sys-usaf-legion-ioc",
    title: "Legion Pod reaches initial operating capability",
    publisher: "U.S. Air Force · Air Combat Command",
    url: "https://www.af.mil/News/Features/Article/2931186/legion-pod-reaches-ioc/",
    published: "2022-02-12",
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "sys-lockheed-legion",
    title: "Legion Pod · multi-function sensor system",
    publisher: "Lockheed Martin",
    url: "https://www.lockheedmartin.com/en-us/products/legion-pod.html",
    published: null,
    accessed: "2026-09-09",
    evidence: "manufacturer",
  },
  {
    id: "sys-lockheed-sniper-integration",
    title: "Sniper pod production approval under ATP-SE · F-15E integration",
    publisher: "Lockheed Martin",
    url: "https://news.lockheedmartin.com/2013-01-16-Lockheed-Martin-Receives-U-S-Air-Force-Approval-For-Sniper-Pod-Full-Rate-Production-Under-ATP-SE-Program",
    published: "2013-01-16",
    accessed: "2026-09-09",
    evidence: "manufacturer",
  },
  {
    id: "sys-lockheed-sniper",
    title: "Sniper Advanced Targeting Pod",
    publisher: "Lockheed Martin",
    url: "https://www.lockheedmartin.com/en-us/products/sniper.html",
    published: null,
    accessed: "2026-09-09",
    evidence: "manufacturer",
  },
  {
    id: "sys-boeing-korea-parts",
    title: "Boeing completes F-15K deliveries · Korean industrial partners",
    publisher: "Boeing",
    url: "https://boeing.mediaroom.com/2012-04-03-Boeing-Completes-On-cost-On-schedule-Delivery-of-F-15K-Slam-Eagles-to-Korea",
    published: "2012-04-03",
    accessed: "2026-09-09",
    evidence: "manufacturer",
  },
  {
    id: "sys-usaf-ofp-test",
    title: "Operational Test advances at Northern Edge 21 · F-15 software and sensors",
    publisher: "U.S. Air Force · 53rd Wing",
    url: "https://www.afmc.af.mil/News/Article-Display/Article/2621292/for-the-warfighter-operational-test-advances-at-ne21/",
    published: "2021-05-17",
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "sys-usaf-robins-installation",
    title: "561st AMXS completes first F-15E depot EPAWSS installation",
    publisher: "U.S. Air Force · 78th Air Base Wing Public Affairs",
    url: "https://www.edwards.af.mil/News/AFMC-News/Article/4167384/561st-amxs-completes-first-f-15e-pdm-epawss-installation/",
    published: "2025-04-25",
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "sys-usaf-epawss-delivery",
    title: "First EPAWSS-equipped F-15Es arrive at RAF Lakenheath",
    publisher: "U.S. Air Force · 48th Fighter Wing Public Affairs",
    url: "https://www.af.mil/News/Article-Display/Article/4034876/first-f-15e-strike-eagles-equipped-with-advanced-epawss-system-arrive-at-libert/",
    published: "2025-01-21",
    accessed: "2026-09-09",
    evidence: "government",
  },
  {
    id: "sys-raytheon-vx-announcement",
    title: "RTX unveils APG-82(V)X radar enhanced with gallium nitride",
    publisher: "Raytheon · RTX",
    url: "https://www.rtx.com/news/news-center/2025/09/23/rtx-unveils-new-apg-82vx-radar-enhanced-with-gallium-nitride",
    published: "2025-09-23",
    accessed: "2026-09-09",
    evidence: "manufacturer",
  },
];

export const F15_SYSTEMS: SystemContext[] = [
  {
    id: "boeing-airframe",
    category: "supplier",
    title: "Airframe and final integration",
    organization: "Boeing · McDonnell Douglas heritage",
    variants: ["A/B/C/D/E heritage", "EX production"],
    usVariants: ["A", "B", "C", "D", "E", "EX"],
    summary: "The legacy Eagle fact sheet identifies McDonnell Douglas as the aircraft contractor. Boeing builds the F-15EX in St. Louis and integrates its systems. The EX acquisition report records separate purchases of engines, radars and avionics from their original manufacturers: the Boeing airframe contract alone is not the full aircraft cost.",
    asOf: "2025-01-17",
    sourceIds: ["sys-usaf-eagle-facts", "sys-usaf-epawss-industry", "sys-ex-msar2023"],
    recordSlugs: ["F015EX"],
  },
  {
    id: "ge-f110-engine",
    category: "supplier",
    title: "F110-GE-129 engines",
    organization: "GE Aerospace",
    variants: ["EX"],
    usVariants: ["EX"],
    summary: "GE supplies the F110 engines for the U.S. F-15EX. The Air Force's October 2021 award covered installed engines and spares, with additional options. Engine quantities therefore differ from aircraft quantities, and an option is not a delivered engine. The separate engine award should not be added to a program total without checking overlap.",
    asOf: "2021-10-29",
    sourceIds: ["sys-usaf-f110-contract", "sys-ge-f110"],
  },
  {
    id: "pratt-f100-engine",
    category: "supplier",
    title: "F100 engine family",
    organization: "Pratt & Whitney",
    variants: ["A/B/C/D", "E · configuration-dependent"],
    usVariants: ["A", "B", "C", "D", "E"],
    summary: "Pratt & Whitney's F100 powers legacy Eagles. Air Force references identify several engine versions; the Strike Eagle uses F100-PW-220 or -229 engines, while the museum identifies -220 use on C/D/E models. A variant label alone does not identify the engine installed on a particular aircraft. These references do not establish a current spare-engine purchase.",
    asOf: "2019-04",
    sourceIds: ["sys-usaf-eagle-facts", "sys-usaf-strike-facts", "sys-usaf-f100"],
  },
  {
    id: "raytheon-apg82-radar",
    category: "supplier",
    title: "APG-82 radar and radar modernization",
    organization: "Raytheon · RTX",
    variants: ["E · upgraded aircraft", "EX"],
    usVariants: ["E", "EX"],
    summary: "The APG-82 uses electronic scanning to find and track air and ground targets. The F-15E Radar Modernization Program replaces its older APG-70 radar; the F-15EX also uses APG-82. The December 2022 acquisition report identifies Raytheon radars supplied to Boeing as government-furnished equipment for EX Lot 3. This is a component relationship, not a radar-cost allocation across every Eagle.",
    asOf: "2022-12",
    sourceIds: ["sys-raytheon-apg82", "sys-usaf-radar-first-flight", "sys-ex-sar2022"],
  },
  {
    id: "elbit-cockpit-displays",
    category: "supplier",
    title: "Cockpit displays",
    organization: "Elbit",
    variants: ["EX"],
    usVariants: ["EX"],
    summary: "The Air Force's F-15EX acquisition report names Elbit large-area and low-profile head-up displays among contractor-furnished parts. These are the displays the crew reads inside the cockpit and through the head-up view. The report also shows why seemingly small components matter to delivery schedules. Its December 2023 risk snapshot is historical, not proof of a continuing shortage today.",
    asOf: "2023-12-31",
    sourceIds: ["sys-ex-msar2023"],
  },
  {
    id: "bae-flight-control-computers",
    category: "supplier",
    title: "Digital flight-control computers",
    organization: "BAE Systems",
    variants: ["EX"],
    usVariants: ["EX"],
    summary: "BAE says it makes the computers that translate pilot inputs and aircraft-sensor readings into commands for the EX's control surfaces. In August 2024, Boeing selected BAE to refresh their hardware and software. This supplier statement identifies an upgrade effort; it does not show that every aircraft already has the refreshed computer.",
    asOf: "2024-08-20",
    sourceIds: ["sys-bae-flight-controls"],
  },
  {
    id: "epawss-system",
    category: "supplier",
    title: "EPAWSS electronic protection",
    organization: "BAE Systems · Boeing integration",
    variants: ["E · modified aircraft", "EX"],
    usVariants: ["E", "EX"],
    summary: "EPAWSS helps aircrew identify, locate and counter electronic threats. The Air Force identifies BAE as the manufacturer in Nashua, New Hampshire, and Boeing as the integrator in San Antonio, Texas; new EX aircraft include the system. E-model installation procurement and shared system development are separate records, and neither supplies a per-variant allocation of all EPAWSS spending.",
    asOf: "2025-01-17",
    sourceIds: ["sys-usaf-epawss-industry"],
    recordSlugs: ["0207171F", "F15EWS"],
  },
  {
    id: "lockheed-legion-pod",
    category: "supplier",
    title: "Legion Pod infrared search and track",
    organization: "Lockheed Martin",
    variants: ["C · documented fielding"],
    usVariants: ["C"],
    summary: "Legion Pod adds an infrared sensor for finding and tracking aircraft when radar use is difficult. The Air Force reported initial operating capability on the F-15C in January 2022. Lockheed identifies the IRST21 sensor and processor inside the pod. This documented C-model milestone does not establish installation across all Eagle variants or the current pod inventory.",
    asOf: "2022-02-12",
    sourceIds: ["sys-usaf-legion-ioc", "sys-lockheed-legion"],
  },
  {
    id: "lockheed-sniper-pod",
    category: "supplier",
    title: "Sniper targeting pod",
    organization: "Lockheed Martin",
    variants: ["E · documented integration"],
    usVariants: ["E"],
    summary: "Sniper combines visible-light and infrared imaging with laser designation and video sharing. Lockheed's 2013 production announcement identified ATP-SE integration on the F-15E, alongside other aircraft. It is mission equipment carried by aircraft, not a permanent feature of every F-15. Manufacturer-wide pod delivery counts should not be read as an F-15 purchase total.",
    asOf: "2013-01-16",
    sourceIds: ["sys-lockheed-sniper-integration", "sys-lockheed-sniper"],
  },
  {
    id: "korean-industrial-parts",
    category: "supplier",
    title: "Wings, fuselage, wiring and landing gear",
    organization: "Korean industrial partners · Boeing F-15K program",
    variants: ["K · 2012 production account"],
    usVariants: [],
    summary: "Boeing's F-15K delivery account names Korea Aerospace Industries for wings and forward fuselages, Huneed for wire harnesses, Hanwha for hydraulic and flight-control actuators, and WIA for landing gear. These are the company names and roles reported in April 2012. They describe an international production network, not a current supplier list for every U.S. F-15EX.",
    asOf: "2012-04-03",
    sourceIds: ["sys-boeing-korea-parts"],
  },
  {
    id: "operational-flight-program",
    category: "related",
    title: "Operational Flight Program: the software layer",
    organization: "U.S. Air Force operational and developmental test teams",
    variants: ["C/E/EX · cited test account"],
    usVariants: ["C", "E", "EX"],
    summary: "The OFP coordinates mission software with sensors, weapons and cockpit hardware. At Northern Edge 2021, the Air Force tested C/E software alongside a related EX suite, including a data-transfer upgrade. That dated test story explains why an aircraft can gain capability without changing its silhouette. The linked PE covers shared software and integration; it is not a price for an individual cockpit.",
    asOf: "2021-05-17",
    sourceIds: ["sys-usaf-ofp-test"],
    recordSlugs: ["0207134F"],
  },
  {
    id: "robins-depot-modernization",
    category: "related",
    title: "Depot work: upgrades during heavy maintenance",
    organization: "561st Aircraft Maintenance Squadron · Robins AFB, Georgia",
    variants: ["E"],
    usVariants: ["E"],
    summary: "Robins completed its first F-15E EPAWSS installation during scheduled depot maintenance in March 2025. The Air Force describes combining the work with structural and communications modifications so an aircraft need not make a separate upgrade visit. Spending on a mature fleet includes people, wiring, structural repairs and installation work as well as new equipment.",
    asOf: "2025-04-25",
    sourceIds: ["sys-usaf-robins-installation"],
    recordSlugs: ["F15EWS"],
  },
  {
    id: "epawss-frontline-delivery",
    category: "development",
    title: "Delivered: EPAWSS reaches front-line F-15Es",
    organization: "48th Fighter Wing · RAF Lakenheath",
    variants: ["E"],
    usVariants: ["E"],
    summary: "The Air Force reported that two upgraded F-15Es arrived at RAF Lakenheath on January 16, 2025, with one assigned to each of its F-15E squadrons. This confirms a fielding milestone, not completion of the fleet-wide retrofit. Delivery evidence gives the budget story a concrete outcome while preserving the difference between an installed upgrade and an aircraft purchase.",
    asOf: "2025-01-21",
    sourceIds: ["sys-usaf-epawss-delivery"],
    recordSlugs: ["F15EWS"],
  },
  {
    id: "apg82-vx-announcement",
    category: "development",
    title: "Announced: a new APG-82 radar generation",
    organization: "Raytheon · RTX",
    variants: ["APG-82 family · proposed next generation"],
    usVariants: [],
    summary: "Raytheon unveiled APG-82(V)X on September 23, 2025, describing a gallium-nitride radar with updated processing. The company said development had begun in El Segundo and identified Forest, Mississippi, for production. This is a manufacturer announcement; it does not establish an Air Force order, an approved F-15EX retrofit or a fielded capability.",
    asOf: "2025-09-23",
    sourceIds: ["sys-raytheon-vx-announcement"],
  },
];
